#ifndef __plot_psrfits_cmd__
#define __plot_psrfits_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -m: Mask filename */
  char maskfileP;
  char* maskfile;
  int maskfileC;
  /***** -verbose: Debugging mode */
  char verboseP;
  /***** -fbin: Power-of-2 number of samples to average in frequency */
  char fbinP;
  int fbin;
  int fbinC;
  /***** -tbin: Power-of-2 number of samples to average in time */
  char tbinP;
  int tbin;
  int tbinC;
  /***** -start: Start time of the data to plot */
  char startP;
  float start;
  int startC;
  /***** -end: End time of the data to plot */
  char endP;
  float end;
  int endC;
  /***** -dm: DM to dedisperse the data */
  char dmP;
  float dm;
  int dmC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

